"""
Record file: normalizer draft judgments for the 78 ambiguous /
informal_symptom_language rows.

################################################################
IMPORTANT: this is not an automated script. It is a RECORD.
################################################################

This is different from normalize_slang.py, which is designed to
actually call the Anthropic API (via the `Anthropic()` client and
`client.messages.create()`), looping through rows automatically.

The 78 judgments below did NOT come from an API call. They were
produced manually, row by row, directly in a conversation with
Claude, reading each row's text and generating a judgment, which was
then copy-pasted into JSONL format. No Python code ever ran
normalize_slang.py or hit the model's API endpoint during that
process.

The only purpose of this script is to take the 78 results generated
in that conversation and give them a clear, traceable, code-based
record. Running it writes the data hard-coded below out to
normalizer_predictions.jsonl, but that output is NOT freshly
generated by calling a model. It is simply re-writing data that
already existed into a file.

If the sample needs to be scaled up to n>=100 (the target already
committed to in the paper), the correct approach is to actually run
normalize_slang.py through the API, automated, rather than continuing
with this manual, conversational approach. That approach doesn't
scale, and doesn't leave a reproducible execution record, which is
exactly the gap this script is meant to fill.

Usage:
    python manual_normalizer_record.py
"""

import json
import os

# The 78 entries below are a record of judgments produced manually,
# through a conversation interface, in mid-August 2026. Each row's
# model_literal_or_nonliteral / model_normalized_meaning was generated
# by reading that annotation_id's corresponding comment/title text and
# applying the judgment criteria defined in normalize_slang.py
# (literal / nonliteral / ambiguous, plus a plain-language paraphrase)
# by hand. These are not the output of a model API call.
MANUAL_PREDICTIONS = [
    {"annotation_id": "yt_0100", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Feeling more energetic and experiencing less mental fogginess since starting the diet."},
    {"annotation_id": "yt_0101", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Several physical symptoms, including mental fogginess, resolved after starting the diet."},
    {"annotation_id": "yt_0102", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "No longer experiencing mental fogginess or several other symptoms after increasing electrolyte intake on keto."},
    {"annotation_id": "yt_0104", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Mental fogginess and several other chronic health conditions resolved after switching to a low-carb diet."},
    {"annotation_id": "yt_0105", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Noticing improved mental clarity and steadier energy just days into cutting carbs."},
    {"annotation_id": "yt_0106", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Wanting to avoid mental fogginess, inflammation, and low energy by returning to a strict keto lifestyle."},
    {"annotation_id": "yt_0135", "primary_slang": "fighting for my life", "model_literal_or_nonliteral": "nonliteral", "model_normalized_meaning": "A workout was extremely difficult, described humorously."},
    {"annotation_id": "yt_0204", "primary_slang": "fighting for my life", "model_literal_or_nonliteral": "nonliteral", "model_normalized_meaning": "A tough leg-day workout, described humorously as unbearable."},
    {"annotation_id": "yt_0205", "primary_slang": "fighting for my life", "model_literal_or_nonliteral": "nonliteral", "model_normalized_meaning": "Calf raises during the last set were exhausting, described humorously."},
    {"annotation_id": "yt_0206", "primary_slang": "fighting for my life", "model_literal_or_nonliteral": "ambiguous", "model_normalized_meaning": "Used as a podcast/channel tagline; insufficient context to tell whether it refers to a genuine health or life struggle or is purely stylistic branding."},
    {"annotation_id": "yt_0207", "primary_slang": "fighting for my life", "model_literal_or_nonliteral": "nonliteral", "model_normalized_meaning": "Leg day was extremely difficult, described humorously."},
    {"annotation_id": "yt_0272", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "During an IBS flare, experiencing weakness, leg pain, mental fogginess, anxiety, dizziness, and bloating."},
    {"annotation_id": "yt_0273", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Experienced depression, mental fogginess, and bloating before improving diet and self-care habits."},
    {"annotation_id": "yt_0314", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Started creatine hoping it would help with mental fogginess and general wellbeing."},
    {"annotation_id": "yt_0315", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Asking whether others experienced bloating or side effects from a supplement claimed to clear mental fogginess."},
    {"annotation_id": "yt_0316", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Creatine has helped with mental fogginess, sleep, and workout recovery."},
    {"annotation_id": "yt_0317", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Observed coworkers on the medication becoming less friendly and making more mistakes at work, describing it as increased mental fogginess."},
    {"annotation_id": "yt_0318", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Discussing whether a medication's effect on protein and gluconeogenesis could plausibly cause mental fogginess."},
    {"annotation_id": "yt_0319", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Not replacing electrolytes while drinking lots of water can worsen fatigue and mental fogginess."},
    {"annotation_id": "yt_0320", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Experienced headaches and mental fogginess when cutting out sugar, attributed to withdrawal."},
    {"annotation_id": "yt_0321", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Noticed a strong sense of calm and reduced mental fogginess soon after starting the medication."},
    {"annotation_id": "yt_0322", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Feeling clear-headed and free of mental fogginess, with reduced appetite and more calm energy."},
    {"annotation_id": "yt_0336", "primary_slang": "fighting for my life", "model_literal_or_nonliteral": "ambiguous", "model_normalized_meaning": "References doing martial arts while living with Crohn's disease; insufficient visible text to tell whether the phrase describes a literal health struggle or is used more casually."},
    {"annotation_id": "yt_0377", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Identified specific foods that trigger headaches and mental fogginess through years of dietary trial and error."},
    {"annotation_id": "yt_0378", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Doctor is dismissing ongoing mental fogginess, difficulty concentrating, and fatigue as unrelated to a past infection."},
    {"annotation_id": "yt_0379", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Experiencing mental fogginess when trying to change a difficult living situation, in the context of past trauma."},
    {"annotation_id": "yt_0380", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Has had persistent mental fogginess since a traumatic event in adolescence and is trying a new supplement for it."},
    {"annotation_id": "yt_0381", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Certain foods worsen mental fogginess and headaches related to C-PTSD; dietary changes have partially helped."},
    {"annotation_id": "yt_0382", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Reports ongoing mental fogginess since a vaccine, worsening over time."},
    {"annotation_id": "yt_0383", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Experienced severe mental fogginess from overtraining despite good diet and sleep, suggesting factors besides diet contribute to it."},
    {"annotation_id": "yt_0384", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Struggling to identify the cause of excessive but unrefreshing sleep and other symptoms grouped under this term."},
    {"annotation_id": "yt_0385", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "A particular supplement has notably helped with mental fogginess."},
    {"annotation_id": "yt_0386", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Eating whole citrus fruit, rather than juice, helps clear mental fogginess; juice's sugar content can worsen it."},
    {"annotation_id": "yt_0387", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Tracked diet and habits for months and found a specific food that was triggering episodes of mental fogginess."},
    {"annotation_id": "yt_0388", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Video describing a supplement recipe intended to reduce mental fogginess and improve memory and focus."},
    {"annotation_id": "yt_0389", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Sudden severe mental fogginess and other symptoms in 2020 turned out to be linked to gut health and low iron, not a psychiatric issue."},
    {"annotation_id": "yt_0390", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Years of mental fogginess improved significantly after switching from intense exercise to yoga and meditation."},
    {"annotation_id": "yt_0391", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Describing episodes of mental confusion and memory lapses linked to stress and poor sleep, especially around exams."},
    {"annotation_id": "yt_0392", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Experienced mental fogginess and other side effects while adjusting antidepressant dosage."},
    {"annotation_id": "yt_0393", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Feels the video's advice was too narrowly focused on diet as the cause of mental fogginess."},
    {"annotation_id": "yt_0394", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Decades on keto have eliminated mental fogginess and improved energy and mood."},
    {"annotation_id": "yt_0395", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Mental fogginess began during perimenopause and improved greatly with estrogen treatment rather than diet changes."},
    {"annotation_id": "yt_0396", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "A carnivore diet worsened mental fogginess, which resolved after reintroducing fruit, attributed to hormone-related changes."},
    {"annotation_id": "yt_0397", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Video summarizing how blood sugar spikes and post-meal inflammation contribute to reduced mental clarity."},
    {"annotation_id": "yt_0398", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Debilitating mental fogginess suspected to be caused by candida, worsened by carbohydrates; planning a major diet change."},
    {"annotation_id": "yt_0399", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Asking others what specific treatments or lifestyle changes fully resolved their chronic mental fogginess."},
    {"annotation_id": "yt_0400", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Describing ongoing dizziness, mental fogginess, and blurry vision since a health incident following COVID and steroid treatment."},
    {"annotation_id": "yt_0401", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Experiencing persistent mental fogginess despite a healthy diet, exercise, and supplements, seeking help."},
    {"annotation_id": "yt_0402", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Suggesting that nutrient deficiencies or insulin resistance, not just posture, may explain fatigue and mental fogginess."},
    {"annotation_id": "yt_0403", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Teenager describing persistent mental fogginess since having COVID, seeking advice despite dismissive doctors."},
    {"annotation_id": "yt_0404", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "A psychiatrist explaining that mental fogginess usually has an underlying physical cause rather than being laziness."},
    {"annotation_id": "yt_0405", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Describing personal coping strategies, like napping and quiet activities, for frequent mental fogginess."},
    {"annotation_id": "yt_0406", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Long-term mental fogginess suspected to be linked to diet and living environment, worsened by financial hardship."},
    {"annotation_id": "yt_0407", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Persistent mental fogginess and memory problems after stopping psychiatric medication abruptly, significantly affecting daily life."},
    {"annotation_id": "yt_0408", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Experiencing heartburn, gas, mental fogginess, and low mood after eating, with only temporary relief from medication."},
    {"annotation_id": "yt_0409", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Listing lifestyle habits believed to help prevent mental fogginess."},
    {"annotation_id": "yt_0410", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "A high-sugar morning caused severe mental fogginess and difficulty concentrating at work."},
    {"annotation_id": "yt_0411", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Video summary explaining gut health, nutrient deficiencies, and hormones as causes of mental fogginess."},
    {"annotation_id": "yt_0412", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Asking others what specific treatments or lifestyle changes fully resolved their chronic mental fogginess."},
    {"annotation_id": "yt_0413", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Severe mental fogginess linked to stress and sleep deprivation from an abusive relationship."},
    {"annotation_id": "yt_0414", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Video summary listing dietary and lifestyle strategies to reduce mental fogginess."},
    {"annotation_id": "yt_0415", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Sleep quality is the biggest factor determining whether mental fogginess occurs, with hormones also playing a role."},
    {"annotation_id": "yt_0422", "primary_slang": "fighting for my life", "model_literal_or_nonliteral": "nonliteral", "model_normalized_meaning": "An ironic joke about a paramedic needing emergency help themselves, used for comedic effect."},
    {"annotation_id": "yt_0423", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "A particular melatonin dose and timing eliminated mental fogginess that a different dose had caused."},
    {"annotation_id": "yt_0424", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Living with chronic fatigue syndrome, including crippling fatigue, poor sleep, and mental fogginess, for eight years."},
    {"annotation_id": "yt_0425", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "A list of confusing chronic-illness symptoms being searched online, including mental fogginess, fatigue, and forgetfulness."},
    {"annotation_id": "yt_0426", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Magnesium seemed to relieve depression symptoms and mental fogginess after the first dose."},
    {"annotation_id": "yt_0427", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Running out of magnesium glycinate brought back mental fogginess and fatigue, which resolved once resuming it."},
    {"annotation_id": "yt_0428", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Gradual walking and a keto diet have reduced mental fogginess and increased energy while managing chronic fatigue."},
    {"annotation_id": "yt_0459", "primary_slang": "knocked me out", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "A sleep-gummy product caused a strong sedative effect, described as a marketing claim for the product."},
    {"annotation_id": "yt_0460", "primary_slang": "knocked me out", "model_literal_or_nonliteral": "ambiguous", "model_normalized_meaning": "A sleep-drink product review; the visible title does not include the slang phrase, so context is insufficient to judge literalness."},
    {"annotation_id": "yt_0461", "primary_slang": "knocked me out", "model_literal_or_nonliteral": "ambiguous", "model_normalized_meaning": "A sleep-drink product review; the visible title does not include the slang phrase, so context is insufficient to judge literalness."},
    {"annotation_id": "yt_0462", "primary_slang": "knocked me out", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "A sleep-gummy product caused a strong sedative effect, described as a marketing claim for the product."},
    {"annotation_id": "yt_0463", "primary_slang": "knocked me out", "model_literal_or_nonliteral": "ambiguous", "model_normalized_meaning": "A sleep-drink product review; the visible title does not include the slang phrase, so context is insufficient to judge literalness."},
    {"annotation_id": "yt_0464", "primary_slang": "knocked me out", "model_literal_or_nonliteral": "ambiguous", "model_normalized_meaning": "A sleep-drink product review; the visible title does not include the slang phrase, so context is insufficient to judge literalness."},
    {"annotation_id": "yt_0465", "primary_slang": "knocked me out", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "A sleep smoothie caused a strong sedative effect within 15 minutes, described as a marketing claim for the product."},
    {"annotation_id": "yt_0466", "primary_slang": "knocked me out", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "A sleep smoothie caused a strong sedative effect within 15 minutes, described as a marketing claim for the product."},
    {"annotation_id": "yt_0482", "primary_slang": "brain fog", "model_literal_or_nonliteral": "literal", "model_normalized_meaning": "Using nicotine as a teenager with undiagnosed ADHD immediately relieved mental fogginess."},
]

OUTPUT_PATH = "data_raw/normalizer_predictions.jsonl"


def main():
    assert len(MANUAL_PREDICTIONS) == 78, f"Expected 78 rows, got {len(MANUAL_PREDICTIONS)}"

    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)

    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        for record in MANUAL_PREDICTIONS:
            f.write(json.dumps(record, ensure_ascii=False) + "\n")

    print(f"Wrote {len(MANUAL_PREDICTIONS)} records: {OUTPUT_PATH}")
    print()
    print("Note: this output was not freshly generated by calling a model API.")
    print("It is simply the existing manual judgment record re-written to a file.")
    print("To scale the sample up to n>=100, use normalize_slang.py to process")
    print("new rows through the API instead of continuing with this manual")
    print("record-keeping approach.")


if __name__ == "__main__":
    main()